apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::470827032215:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9PJXMMB2IE3W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<470827032215>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T22:31:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1664"
  uid: bbc7cf82-fb42-4ef6-9996-a957aa1d28ed
