apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::446672237007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16EBAQ0F577PT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::446672237007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::446672237007:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T20:08:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1905"
  uid: 529570db-84c5-4c73-b512-ee528a71efc7
